#!/usr/bin/env node
'use strict';

/**
 * Generates the Soft and Dimmed variants from the base theme.
 *
 * `themes/neon-pink-dark-color-theme.json` is the single hand-maintained
 * source. Every other theme in `contributes.themes` is produced from it, so a
 * color added to the base reaches all three variants instead of having to be
 * back-filled twice.
 *
 * The base theme leaves almost no contrast headroom on purpose — its darkest
 * token, the `#FF2DBE` accent, measures 4.74:1 inside a selection against a
 * 4.5:1 floor. A naive "desaturate and lighten the background" transform
 * spends that headroom immediately and drops the accent to 4.2:1. So the
 * transform is built to move contrast as little as possible:
 *
 *   1. Desaturation at constant luminance. Each color is pulled toward the
 *      gray of its own HSL lightness, then scaled back to the WCAG relative
 *      luminance it started with. Hue is untouched. Because contrast is a
 *      function of luminance alone, this step cannot change a single ratio —
 *      the variants look calmer without measuring worse.
 *   2. Background lift. Pure black becomes the variant's own base tint, and
 *      the rest of the dark surface ramp is lifted by a decreasing amount that
 *      reaches zero at LIFT_CEILING. This is the one step that costs contrast,
 *      because every foreground now sits on a brighter floor.
 *   3. Foreground gain. Everything above LIFT_CEILING — the foregrounds — is
 *      scaled in luminance by exactly what the lifted editor background took
 *      away, so a token keeps the ratio it had on pure black. The gain is
 *      about 3%, far too small to see, which is why the variants still read as
 *      softer rather than brighter.
 *
 * What is left over is the surfaces that are lifted *more* than the editor
 * background: a selection, a changed word in a diff. Those are still a hair
 * below where they started, which is why `npm test` measures every variant in
 * full rather than trusting the derivation.
 *
 * Alpha is preserved byte-for-byte; a fully transparent color is left alone
 * because lifting something invisible only makes the diff noisy.
 *
 * Usage:
 *   node scripts/build-themes.js            write the generated themes
 *   node scripts/build-themes.js --check    fail if what is on disk is stale
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const THEMES_DIR = path.join(ROOT, 'themes');
const BASE_FILE = 'neon-pink-dark-color-theme.json';

const NOTE =
  'Generated by scripts/build-themes.js from ' +
  BASE_FILE +
  ' — do not edit by hand. Run `npm run build` after changing the base theme.';

/**
 * The HSL lightness that separates a surface from a foreground. The base
 * theme's surface ramp tops out at `#7A0049` (L 0.24) and its darkest
 * foreground, `#B3689B`, sits at L 0.55, so 0.35 has room on both sides.
 * Below it a color is lifted; above it a color is gained.
 */
const LIFT_CEILING = 0.35;

const VARIANTS = [
  {
    label: 'Neon Pink Dark Soft',
    file: 'neon-pink-dark-soft-color-theme.json',
    saturation: 0.8,
    base: '#12000A',
  },
  {
    label: 'Neon Pink Dimmed',
    file: 'neon-pink-dimmed-color-theme.json',
    saturation: 0.6,
    base: '#0D0008',
  },
];

// ---------------------------------------------------------------------------
// color math
// ---------------------------------------------------------------------------

const COLOR_RE = /^#([0-9a-f]{6})([0-9a-f]{2})?$/i;

function parseHex(hex) {
  const m = COLOR_RE.exec(hex.trim());
  if (!m) return null;
  const n = parseInt(m[1], 16);
  return {
    r: (n >> 16) & 0xff,
    g: (n >> 8) & 0xff,
    b: n & 0xff,
    alpha: m[2] === undefined ? null : m[2].toUpperCase(),
  };
}

function toHex({ r, g, b }, alpha) {
  const h = (v) =>
    Math.round(Math.min(255, Math.max(0, v)))
      .toString(16)
      .padStart(2, '0')
      .toUpperCase();
  return `#${h(r)}${h(g)}${h(b)}${alpha || ''}`;
}

const toLinear = (v) => {
  const s = Math.min(1, Math.max(0, v / 255));
  return s <= 0.04045 ? s / 12.92 : Math.pow((s + 0.055) / 1.055, 2.4);
};

const fromLinear = (v) => {
  const s = Math.min(1, Math.max(0, v));
  return 255 * (s <= 0.0031308 ? s * 12.92 : 1.055 * Math.pow(s, 1 / 2.4) - 0.055);
};

/** WCAG 2.1 relative luminance, 0–1. */
function luminance({ r, g, b }) {
  return 0.2126 * toLinear(r) + 0.7152 * toLinear(g) + 0.0722 * toLinear(b);
}

/** HSL lightness, 0–1. */
function lightness({ r, g, b }) {
  return (Math.max(r, g, b) + Math.min(r, g, b)) / 2 / 255;
}

/** Rescale a color in linear light until it measures `target`. */
function withLuminance(c, target) {
  const y = luminance(c);
  if (y <= 0 || target <= 0) return c;
  const t = target / y;
  return {
    r: fromLinear(toLinear(c.r) * t),
    g: fromLinear(toLinear(c.g) * t),
    b: fromLinear(toLinear(c.b) * t),
  };
}

/** Scale HSL saturation by `factor`, leaving hue and lightness where they are. */
function desaturate(c, factor) {
  const gray = lightness(c) * 255;
  return {
    r: gray + (c.r - gray) * factor,
    g: gray + (c.g - gray) * factor,
    b: gray + (c.b - gray) * factor,
  };
}

/** Add the variant's base tint to a dark surface, fading out at LIFT_CEILING. */
function lift(c, base) {
  const k = 1 - lightness(c) / LIFT_CEILING;
  return { r: c.r + base.r * k, g: c.g + base.g * k, b: c.b + base.b * k };
}

// ---------------------------------------------------------------------------
// generation
// ---------------------------------------------------------------------------

function convert(value, variant) {
  const c = parseHex(value);
  if (!c) return value;
  // A fully transparent slot carries no color — `minimap.background` and
  // `tab.activeBorder` are switches, not swatches.
  if (c.alpha === '00') return value;

  const calm = withLuminance(desaturate(c, variant.saturation), luminance(c));
  const out =
    lightness(calm) < LIFT_CEILING
      ? lift(calm, variant.baseColor)
      : withLuminance(calm, variant.gain(luminance(calm)));
  return toHex(out, c.alpha);
}

/** Walk the theme, rewriting every string that parses as a color. */
function mapColors(node, variant) {
  if (typeof node === 'string') return convert(node, variant);
  if (Array.isArray(node)) return node.map((v) => mapColors(v, variant));
  if (node && typeof node === 'object') {
    const out = {};
    for (const [k, v] of Object.entries(node)) out[k] = mapColors(v, variant);
    return out;
  }
  return node;
}

/**
 * How much luminance a foreground has to gain to keep the contrast it had
 * against the base theme's editor background, now that the variant's editor
 * background sits above it.
 */
function gainFor(baseEditorY, variantEditorY) {
  const scale = (variantEditorY + 0.05) / (baseEditorY + 0.05);
  return (y) => (y + 0.05) * scale - 0.05;
}

function build(base, variant) {
  const baseColor = parseHex(variant.base);
  const resolved = {
    ...variant,
    baseColor,
    gain: gainFor(luminance(parseHex(base.colors['editor.background'])), luminance(baseColor)),
  };

  const mapped = mapColors(base, resolved);
  const out = { name: variant.label, _generated: NOTE };
  for (const [k, v] of Object.entries(mapped)) {
    if (k !== 'name') out[k] = v;
  }
  return JSON.stringify(out, null, 2) + '\n';
}

function main() {
  const check = process.argv.includes('--check');
  const base = JSON.parse(fs.readFileSync(path.join(THEMES_DIR, BASE_FILE), 'utf8'));

  const stale = [];
  for (const variant of VARIANTS) {
    const file = path.join(THEMES_DIR, variant.file);
    const generated = build(base, variant);

    if (check) {
      const current = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : null;
      if (current !== generated) stale.push(variant.file);
      continue;
    }

    fs.writeFileSync(file, generated);
    console.log(
      `wrote themes/${variant.file}  ` +
        `(saturation ${Math.round(variant.saturation * 100)}%, base ${variant.base})`
    );
  }

  if (!check) return;

  if (stale.length) {
    console.error(
      `${stale.length} generated theme(s) out of date: ${stale.join(', ')}\n` +
        'The base theme changed without the variants being rebuilt. Run `npm run build`.'
    );
    process.exit(1);
  }
  console.log(`${VARIANTS.length} generated themes up to date with themes/${BASE_FILE}`);
}

main();
